In [1]:
# Very important library in Python
# Used to process Numbers and there Calculations
# Not so popular
# In reality we don't use Numpy directly 

## In Python list elements are not stored sequentially , in Numpy arrays are stored like arrays . ##

In [4]:
import numpy as np
n = np.array([1,2,3])
n

array([1, 2, 3])

In [5]:
# Accessing elements is same as in Python List
## MultiIndexing Diffrent ##
nSub = n[[0,1]]
nSub

array([1, 2])

In [6]:
# Getting type of array
n.dtype

dtype('int32')

In [7]:
#changing type of array 
newArray = np.array([1,2,4],dtype = np.float64)
newArray

array([1., 2., 4.])

In [8]:
#Multi Dimension Arrays
C = np.array([[12,11,10],
            [1,2],
            [1,2,3]])
C
#if the numbers of elements don't match in rows warning is given !!

C:\Users\Ravish Kumar\AppData\Local\Temp\ipykernel_12304\494378351.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([[12,11,10],


array([list([12, 11, 10]), list([1, 2]), list([1, 2, 3])], dtype=object)

In [9]:
Md = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
Md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
Md[0][1]

2

In [11]:
Md[1]

array([4, 5, 6])

In [12]:
Md[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [13]:
Md[0][1:]

array([2, 3])

In [14]:
Md[0] = 0
Md
#It automatically fits the size

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
sum(Md[1])

15

In [16]:
#Brodcasting and Vectorised Operations
arr = np.array([1,2,3])
arr += 1
arr

array([2, 3, 4])

In [35]:
_arr = np.array([1,2,3])
arr + _arr

array([2, 3, 4])

In [36]:
# Boolean Arrays
# Not used directly but used for boolean opearations
print(arr)
arr >=3

[2 3 4]


array([False,  True,  True])

In [41]:
print(arr)
arr[arr>2]

[2 3 4]


array([3, 4])

In [20]:
arr[(arr == 0) | (arr == 2)]

array([2])

In [21]:
# Boolean operators return Boolean Arrays which are used for filtering 

In [42]:
a = np.array([1,2,3])

In [45]:
a[a>0]

array([1, 2, 3])

In [46]:
a.mean()

2.0

In [47]:
a[a>a.mean()]

array([3])

In [48]:
#Comparing sizeof in Python and Numpy

In [52]:
i = 10
i.__sizeof__()

28

In [54]:
np.dtype(int).itemsize

4