In [2]:
import numpy as np

In [5]:
#Creating array of size 10 filled with zeroes
tens = np.zeros(10)
tens

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#Create a numpy array with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
np.ones([3,2], dtype='float')

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
x = np.array([[3,2],
    [2,3],
    [1,1]])
x

array([[3, 2],
       [2, 3],
       [1, 1]])

In [15]:
np.ones(x.shape)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create a numpy matrix of 4*4 integers, filled with fives.
np.ones([4,4], dtype = 'int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Given the X python list convert it to an Y numpy array
x= [1,2,3]
np.array(x)

array([1, 2, 3])

In [19]:
# Given the X numpy array, show it's last element
x[-1]

3

In [20]:
# Given the X numpy array, show it's first three elements
x[0:3]

[1, 2, 3]

In [21]:
# Given the X numpy array, show all middle elements
x[len(x)//2]

2

In [22]:
# Given the X numpy array, show the elements in reverse position
x[::-1]

[3, 2, 1]

In [23]:
# Given the X numpy array, show the elements in an odd position
x[::2]

[1, 3]

In [25]:
#Order (sort) the given numpy array
x = [10,15,12]
x.sort()
x

[10, 12, 15]

In [27]:
#Given the X numpy array, make a mask showing negative elements
x = np.array([-1,-2,-3,4,5])
x<0

array([ True,  True,  True, False, False])

In [32]:
#Given the X numpy array, get numbers higher than 5
x = np.array([5,2,25,6,9,-1])
x[x>5]

array([25,  6,  9])

In [33]:
#Given the X numpy array, get numbers equal to 2 or 10
x[(x==2)|(x==0)]

array([2])

In [35]:
#Given the X numpy matrix, show the mean value of its rows
x = np.array([[1,2,3],
            [4,5,6]])
x[1].mean()

5.0

In [36]:
#Given the X numpy array, show the max value of its elements
x.max()

6